server {
    listen       80;
    listen  [::]:80;
    server_name  group.daoha.top;

    # 强制将所有 HTTP 请求重定向到 HTTPS
    rewrite ^(.*) https://$server_name$1 permanent;
}

server {
    listen 443 ssl;
    server_name group.daoha.top;

    # SSL 证书配置 (请确保这里的路径与你在宿主机挂载进容器的路径一致)
    ssl_certificate      /etc/nginx/ssl/_.daoha.top.pem;
    ssl_certificate_key  /etc/nginx/ssl/_.daoha.top.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    # ==========================================
    # 1. 前端页面路由 (处理 HTML、CSS、JS 等静态资源)
    # ==========================================
    location / {
            # 【修改这里】直接使用标准路径
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
    }

    # ==========================================
    # 2. 后端接口反向代理 (处理 Java 数据请求)
    # ==========================================
    # 假设你的前端 JS 代码请求接口都以 /api/ 开头 (例如 /api/login)
    location ^~ /api/ {
        # 转发到名为 group-buy-me 的容器的 8091 端口
        proxy_pass http://group-buy-me-app:8091;

        # 将客户端的真实 IP 和协议等信息传递给 Java 程序
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
    location ^~ /api/myddd/ {
            proxy_pass http://myddd:8091; # 注意这里是用 myddd 容器名
            # ... proxy_set_header 配置 ...
        }

    # ==========================================
    # 3. 错误页面配置
    # ==========================================
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
